#!/usr/bin/env bash
#
# change rofi colors to those generated by 'wal'

# Source the generated colors
source "${HOME}/.cache/wal/colors.sh"

filename="${HOME}/.config/rofi/rofi.conf"
alpha='DD'

main() {
	printf "rofi.color-enabled: true\n" > ${filename}
	printf "rofi.color-window: argb:%s%s, argb:00000000, argb:00000000\n" ${alpha} ${color0:1} >> ${filename}
	# bg, fg, alt-bg, highlight bg, highlight fg
	printf "rofi.color-normal: argb:00%s, %s, argb:00%s, argb:00%s, %s\n" \
		${color0:1} ${color7} ${color0:1} ${color0:1} ${color2} >> ${filename}
	printf "rofi.color-active: argb:00%s, %s, argb:00%s, %s, %s\n" \
		${color0:1} ${color5} ${color0:1} ${color5} ${color2} >> ${filename}
	printf "rofi.color-urgent: argb:00%s, %s, argb:00%s, %s, %s\n\n" \
		${color0:1} ${color2} ${color0:1} ${color2} ${color2} >> ${filename}

	printf "rofi.lines: 15\n" >> ${filename}
	printf "rofi.width: 3850\n" >> ${filename}
	printf "rofi.modi: window, run\n" >> ${filename}
	printf "rofi.case-sensitive: false\n" >>${filename}
	printf "rofi.eh: 2\n" >> ${filename}
	printf "rofi.padding: 750\n" >> ${filename}
	printf "rofi.hide-scrollbar: true\n" >> ${filename}
	printf "rofi.font: System San Francisco Display 25\n" >> ${filename}
}

main
